apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: seedbox
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:v3.39.0
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "(ip rule del table 51820; ip -6 rule del table 51820) || true"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        envFrom:
        - secretRef:
            name: wireguard-config
        volumeMounts:
        - name: tun-device
          mountPath: /dev/net/tun
        ports:
        - name: control
          containerPort: 8000
          protocol: TCP
        - name: qbittorrent
          containerPort: 8080
          protocol: TCP
        - name: airvpn-tcp
          containerPort: 47594
          protocol: TCP
        - name: airvpn-udp
          containerPort: 47594
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: tun-device
        hostPath:
          path: /dev/net/tun
          type: CharDevice