---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: "9.1.22"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
      interval: 12h

