creation_rules:
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age10hukjnxlessdxm6weznke7g4hwv4wteu6n6qygz8v5ywuyz7lajquxjlu7
    - age1nqjp4rlajvczderyvpaf28gf9c55w5zfhgqgms4w269d4gsvtuaqpejr04
    - age19skcsvegz2j856ptuvcpv9ln2v3ux6q75reetxwy0pg47dnfhd0su9wlsg
    - age1spjk5lngagkjt9stwtvqwdnlet20hnd7tavkqvfjd7nt8a26d3uqm69lpf
    - age1fcm0jwfrmx8myz4xm5l74jts5pngmmtve0wh5wc038fl9tzzcydskx5w8k
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?common\.*
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?special_args\.*
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age1fcm0jwfrmx8myz4xm5l74jts5pngmmtve0wh5wc038fl9tzzcydskx5w8k
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?opentofu\.*
- encrypted_regex: ^(data|stringData)$
  key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: flux/.*.yaml
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age10hukjnxlessdxm6weznke7g4hwv4wteu6n6qygz8v5ywuyz7lajquxjlu7
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?hyper\.*
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age1nqjp4rlajvczderyvpaf28gf9c55w5zfhgqgms4w269d4gsvtuaqpejr04
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?k3s-control-plane\.*
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age19skcsvegz2j856ptuvcpv9ln2v3ux6q75reetxwy0pg47dnfhd0su9wlsg
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?k3s-worker1\.*
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age1spjk5lngagkjt9stwtvqwdnlet20hnd7tavkqvfjd7nt8a26d3uqm69lpf
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?k3s-worker2\.*
- key_groups:
  - age:
    - age12cd6wdnk3su0wkedg7lm5uvcg79hqw28yp6e3h6y944wcaj94cgs53w43h
    - age1fcm0jwfrmx8myz4xm5l74jts5pngmmtve0wh5wc038fl9tzzcydskx5w8k
    pgp:
    - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
  path_regex: (\.)?sonicmaster\.*
