---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
parameters:
    server: 192.168.10.100
    share: /mnt/future/medias
    subDir: "/"
# NFSv4.2 optimized for media files
mountOptions: 
  - vers=4.2 
  - rsize=1048576
  - wsize=1048576
  - hard
  - intr
  - timeo=600
  - noatime
# IMPORTANT: Retain to never delete existing data
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
