apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-storage
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: seedbox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-workers
  resources:
    requests:
      storage: 1Gi
