---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-config
  namespace: flux-system
spec:
  interval: 15m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./flux/infrastructure/gateway-api"
  prune: true
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: gateway-api-crds