{
  inputs,
  ...
}:
{
  imports = [
    inputs.disko.nixosModules.default
    inputs.nixos-facter-modules.nixosModules.facter
    inputs.sops-nix.nixosModules.sops
    { config.facter.reportPath = ./facter.json; }
    ./locals.nix
    ./packages.nix
    ./shell.nix
    ./networking.nix
    ./ssh.nix
    ./secrets.nix
    ./users.nix
    ./nix.nix
    ./boot.nix
    ./services.nix
    ./adguard.nix
    ./ddns.nix
    ./disko.nix
    ./firewall.nix
    ./libvrit.nix
    ./minio.nix
    ./nfs.nix
    ../../modules/traefik
    ./snapraid.nix
  ];
}
