{ pkgs, ... }:
{
  imports = [
    ./backups.nix
    ./flaresolverr.nix
    ./gluetun.nix
    ./torrent.nix
  ];

  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  virtualisation.oci-containers.backend = "podman";
  virtualisation.containers.containersConf.settings = {
    network.dns_bind_port = 54;
  };

  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-seedbox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

}
