apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gateway
  namespace: default
  labels:
    vlan: ingress
spec:
  gatewayClassName: cilium
  addresses:
  - type: IPAddress
    value: 192.168.12.100
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
