---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vlan12-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  addresses:
  - type: IPAddress
    value: 192.168.12.100
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vlan21-gateway
  namespace: default
spec:
  gatewayClassName: cilium
  addresses:
  - type: IPAddress
    value: 192.168.21.241
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All 
