---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy-vlan12
  namespace: default
spec:
  loadBalancerIPs: true
  interfaces:
  - enp6s0  # Untagged interface
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ippool-vlan12
  namespace: default
spec:
  blocks:
  - cidr: 192.168.12.100/29  # IP pool on VLAN 12 for gateways
  serviceSelector:
    matchLabels:
      vlan: ingress 
