---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: vlan12-l2-policy
  namespace: default
spec:
  loadBalancerIPs: true
  interfaces:
  - enp6s0  # Untagged interface
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist

