---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k3s-worker1
  namespace: longhorn-system
spec:
  tags:
    - role=worker
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k3s-worker2
  namespace: longhorn-system
spec:
  tags:
    - role=worker
