---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    configuration:
        destinationPath: s3://vaultwarden
        endpointURL: http://192.168.10.100:9000
        s3Credentials:
            accessKeyId:
                name: minio
                key: ACCESS_KEY_ID
            secretAccessKey:
                name: minio
                key: ACCESS_KEY_SECRET
        wal:
            compression: gzip

