---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    configuration:
        destinationPath: s3://backups
        endpointURL: https://s3.ingress.logikdev.fr 
        s3Credentials:
            accessKeyId:
                name: minio
                key: ACCESS_KEY_ID
            secretAccessKey:
                name: minio
                key: ACCESS_KEY_SECRET
        wal:
          compression: gzip
        data:
          compression: gzip

