apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 15
  superuserSecret:
    name: postgres-creds
  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - vaultwarden
        source:
          externalCluster: hyper
  storage:
    storageClass: longhorn
    size: 1Gi
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: minio
  externalClusters:
    - name: hyper
      connectionParameters:
        host: 192.168.10.100
        user: vaultwarden
        dbname: vaultwarden
        sslmode: disable
      password:
        name: vaultwarden-hyper-secret
        key: password
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-scheduled-backup
  namespace: vaultwarden
spec:
  immediate: true
  schedule: "0 0 0 * * *"  # At midnight every day
  backupOwnerReference: self
  cluster:
    name: vaultwarden-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

