apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - env.yaml
  - secrets.yaml 
  - database.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
