apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
    name: vaultwarden
    namespace: vaultwarden
spec:
    cluster:
        name: vaultwarden-db
    method: plugin
    pluginConfiguration:
        name: barman-cloud.cloudnative-pg.io
