creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - pgp:
          - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
        age:
          - age1fcm0jwfrmx8myz4xm5l74jts5pngmmtve0wh5wc038fl9tzzcydskx5w8k
          - age10hukjnxlessdxm6weznke7g4hwv4wteu6n6qygz8v5ywuyz7lajquxjlu7
          - age1hl38qjaje355tl75pldcn4esc4mt8ptmxj8ptjvu33v4r2hfpvhqvh8ak8
          - age1fgpnxsed4jmw5mtkgsfa2k9kat7qruqt98z9s287mmpzvdtqjvts6j82y3
