apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db-restore
  namespace: databases
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 15
  superuserSecret:
    name: postgres-creds
  bootstrap:
    recovery:
      recoveryTarget:
        targetTime: "2025-08-03 14:14:21.00000+02"
      source: origin
  externalClusters:
    - name: origin
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: minio-backups
          serverName: vaultwarden-db
  storage:
    storageClass: longhorn
    size: 1Gi
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    isWALArchiver: true
    parameters:
      barmanObjectName: minio-backups

