creation_rules:
  - path_regex: (secrets.yaml|cloudflare.env)
    key_groups:
      - pgp:
          - F5A34D392D22853E7EB1FA85AC259B4007CB7CE9
        age:
          - age1fcm0jwfrmx8myz4xm5l74jts5pngmmtve0wh5wc038fl9tzzcydskx5w8k
          - age10hukjnxlessdxm6weznke7g4hwv4wteu6n6qygz8v5ywuyz7lajquxjlu7
          - age1hl38qjaje355tl75pldcn4esc4mt8ptmxj8ptjvu33v4r2hfpvhqvh8ak8
          - age1fgpnxsed4jmw5mtkgsfa2k9kat7qruqt98z9s287mmpzvdtqjvts6j82y3
          - age1g3jnzdl8zr7r4efp26zq3wd6u2m625jsts4wgsdk5a8h44kcqe5qmrsrt6
          - age16hmzhh8lfr0rdk3psgv8mddqedh42l99jmrp5j635eyzf4qqec8sdy239d
          - age1cjh9cfmr463ykmqt58xcknu4p95xvgcczdyrqc0rft9ekgfldphqvum9g8
          - age1mzndux87xz4l046a7ac8mceaeuarnfnqyg33ce7jxkf3vc3mmfyqewg8zr
          - age1smw3rsg7fer2vnqqk6d49lkpuf4nlnncjv33ke4e950tguh6qffswh663l
          - age10putr0f0gdsghjhgjw86u8xdwu2rlxl855m9wp6rxe08ttgsh5as9wgzc4
          - age120t654wpge5mj4m3swdn3q9cp0dpesnj9zkr0lkwsun8cqs7lanqq9wjkq # hyper-clone
