---
# HTTPRoute for MinIO S3 API
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-api
  namespace: minio
spec:
  parentRefs:
  - name: vlan12-gateway
    namespace: default
  hostnames:
  - "s3.ingress.logikdev.fr"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: minio
      port: 9000
---
# HTTPRoute for MinIO Console
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-console
  namespace: minio
spec:
  parentRefs:
  - name: vlan12-gateway
    namespace: default
  hostnames:
  - "minio.ingress.logikdev.fr"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: minio-console
      port: 9090
