---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-minio-backup
  namespace: vaultwarden
spec:
  immediate: true
  schedule: "@weekly" 
  backupOwnerReference: self
  cluster:
    name: vaultwarden-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vaultwarden-longhorn-backup
  namespace: vaultwarden
spec:
  immediate: true
  schedule: "@weekly" 
  backupOwnerReference: self
  cluster:
    name: vaultwarden-db
  method: volumeSnapshot


